// templates/angular/layout.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-__NAME_LOWER__-layout',
  template: `
    <div class="__NAME_LOWER__-layout">
      <header>Header</header>
      <main><ng-content></ng-content></main>
      <footer>Footer</footer>
    </div>
  `
})
export class __NAME__LayoutComponent {}

// templates/default/layout.tsx
import { ReactNode } from 'react';

interface __NAME__Props {
  children: ReactNode;
}

export default function __NAME__({ children }: __NAME__Props): JSX.Element {
  return (
    <div className="__NAME_LOWER__-layout">
      <header>Header</header>
      <main>{children}</main>
      <footer>Footer</footer>
    </div>
  );
}
